
export const environment = {
   production: false,
   PROD_API_URL: "https://botmind-back.herokuapp.com/api",
   LOGIN_API_URL: "https://botmind-back.herokuapp.com/api/login",
   LOGOUT_API_URL: "https://botmind-back.herokuapp.com/api/logout",
   CHECKAUTH_API_URL: "https://botmind-back.herokuapp.com/api/checkAuth",
   REGISTER_USER_API_URL: "https://botmind-back.herokuapp.com/api/users/register",
   GET_USER_PROFILE_API_URL: "https://botmind-back.herokuapp.com/api/users/profile",
   UPDATE_USER_PROFILE_API_URL: "https://botmind-back.herokuapp.com/api/users/updateProfile/",
   ADD_NEW_BLOG_API_URL: "https://botmind-back.herokuapp.com/api/blog/addNewBlog",
   GET_ALL_BLOGS_API_URL: "https://botmind-back.herokuapp.com/api/blog/allBlogs",
   GET_SINGLE_BLOG_API_URL: "https://botmind-back.herokuapp.com/api/blog/singleBlog/",
   GET_BLOGS_FOR_USER_API_URL: "https://botmind-back.herokuapp.com/api/blog/blogs/",
   UPDATE_BLOG_API_URL: "https://botmind-back.herokuapp.com/api/blog/updateBlog",
   DELETE_BLOG_API_URL: "https://botmind-back.herokuapp.com/api/blog/deleteBlog/",
   LIKE_A_BLOG_API_URL: "https://botmind-back.herokuapp.com/api/blog/like",
   DISLIKE_A_BLOG_API_URL: "https://botmind-back.herokuapp.com/api/blog/dislike",
   COMMENT_A_BLOG_API_URL: "https://botmind-back.herokuapp.com/api/blog/comment",
   CHECK_EMAIL_API_URL: "https://botmind-back.herokuapp.com/api/users/checkEmail/",
   CHECK_USERNAME_API_URL: "https://botmind-back.herokuapp.com/api/users/checkUsername/",
    DELETE_USER_ACCOUNT_API_URL: "https://botmind-back.herokuapp.com/api/users/deleteAccount",
   GET_ALL_USERS_API_URL: "https://botmind-back.herokuapp.com/api/users/getAllUsers",
   MONGODB_USER_PASS:"Akladekouassi:Akladekouassi",
   MONGODB_URL:"cluster0.8stux.mongodb.net",
   MONGODB_NAME: "Botmind",
   MONGODB_AUTH_SOURCE:"admin ",
   MONGODB_AUTH_MECHANISME:"SCRAM-SHA-1"
};
