
export const environment = {
   production: true,
   LOCAL_API_URL: "http://localhost:5000",
   PROD_API_URL: "https://heroku.com",
   LOGIN_API_URL: "http://localhost:5000/login",
   LOGOUT_API_URL: "http://localhost:5000/logout",
   CHECKAUTH_API_URL: "http://localhost:5000/checkAuth",
   REGISTER_USER_API_URL: "http://localhost:5000/users/register",
   GET_USER_PROFILE_API_URL: "http://localhost:5000/users/profile",
   UPDATE_USER_PROFILE_API_URL: "http://localhost:5000/users/updateProfile/",
   ADD_NEW_BLOG_API_URL: "http://localhost:5000/blog/addNewBlog",
   GET_ALL_BLOGS_API_URL: "http://localhost:5000/blog/allBlogs",
   GET_SINGLE_BLOG_API_URL: "http://localhost:5000/blog/singleBlog/",
   GET_BLOGS_FOR_USER_API_URL: "http://localhost:5000/blog/blogs/",
   UPDATE_BLOG_API_URL: "http://localhost:5000/blog/updateBlog",
   DELETE_BLOG_API_URL: "http://localhost:5000/blog/deleteBlog/",
   LIKE_A_BLOG_API_URL: "http://localhost:5000/blog/like",
   DISLIKE_A_BLOG_API_URL: "http://localhost:5000/blog/dislike",
   COMMENT_A_BLOG_API_URL: "http://localhost:5000/blog/comment",
   CHECK_EMAIL_API_URL: "http://localhost:5000/users/checkEmail/",
   CHECK_USERNAME_API_URL: "http://localhost:5000/users/checkUsername/",
   DELETE_USER_ACCOUNT_API_URL: "http://localhost:5000/users/deleteAccount",
   GET_ALL_USERS_API_URL: "http://localhost:5000/users/getAllUsers",
   MONGODB_USER_PASS:"Akladekouassi:Akladekouassi",
   MONGODB_URL:"cluster0.8stux.mongodb.net",
   MONGODB_NAME: "Botmind",
   MONGODB_AUTH_SOURCE:"admin ",
   MONGODB_AUTH_MECHANISME:"SCRAM-SHA-1"
};
